name: Go test

on:
   push:
      branches: [master]
   pull_request:
      branches: [master]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3

         - name: Set up Go
           uses: actions/setup-go@v3
           with:
              go-version: 1.18

         - name: utils test
           run: cd server/utils && go test -v

         - name: product logger test
           run: cd product_logger && go test -v

         - name: server test
           run: cd server && go test -v

         - name: coin product test
           run: cd server/coin_products && go test -v
